### ISSUE TITLE
Plot whiskers

### ISSUE THREAD

**Issue by ottapav** [qpsolvers/qpsolvers_benchmark#52]
1) When plotting primal_residual, and similarly for dual_residual, the plots have whiskers (see end of the orange line on the plot below).
![image](https://user-images.githubusercontent.com/10757098/219604439-74a3b41d-37e7-44bc-a85b-40fed12fcd59.png)

2) When typing: python qpsolvers_benchmark\benchmark.py maros_meszaros_dense plot dual_residual high_accuracy --solvers ecos cvxopt scs osqp qpSWIFT 
the qpSWIFT data are missing due to case sensitivity with no warning. Maybe the data plot could be insensitive to the letter cases.
![image](https://user-images.githubusercontent.com/10757098/219604673-16c44bdc-0330-498f-a3f3-cb5727b54342.png)

**Comment by stephane-caron** [comment]
I can reproduce the whiskers :cat:  

```console
$ ./benchmark.py maros_meszaros_dense plot primal_residual high_accuracy                        
```

![image](https://user-images.githubusercontent.com/1189580/220139319-b6889932-03f1-442c-ac90-f811def92e58.png)

**Comment by stephane-caron** [comment]
As a matter of fact, I think it makes sense to trim solutions that don't respect the tolerance requirement. Follow-up in https://github.com/qpsolvers/qpsolvers_benchmark/pull/54.

**Comment by stephane-caron** [comment]
@ottapav Whoops, almost missed your second point. Feel free to open separate issues.

Let me move it to https://github.com/qpsolvers/qpsolvers_benchmark/issues/55
