### ISSUE TITLE
Add benchmark option maros_meszaros_dense_posdef for running dense convex problems only

### ISSUE THREAD

**Issue by ottapav** [qpsolvers/qpsolvers_benchmark#58]
Please consider the feature of running only strictly convex problems, as some solvers can solve QP with strictly positive definite Hessian (P>0) only. If those solvers are running a complete set of problems, the results may look (unfairly) unattractive:
![image](https://user-images.githubusercontent.com/10757098/220956773-98357de0-6f5f-4474-9e28-8b4b45770c5b.png)

For example, ECOS warns that you cannot solve some of the problems in the command line:
![image](https://user-images.githubusercontent.com/10757098/220958052-762c71e3-378b-49d6-a7f0-55f0d2551b36.png)

**Comment by stephane-caron** [comment]
Yes, Maros-Meszaros problems are designed to be difficult so many problems are not strictly convex.

If it's relevant to your use case, it's totally possible to add a ``maros_meszaros_dense_psd`` subset of the test set to the benchmark. You can take a look at how [`maros_meszaros_dense.py`](https://github.com/qpsolvers/qpsolvers_benchmark/blob/e4965731e314df9c8b2e4422846f2f356bdeba95/qpsolvers_benchmark/test_sets/maros_meszaros_dense.py) defines a 

```python
class MarosMeszarosDense(MarosMeszaros):
```

Similarly, a ``maros_meszaros_dense_psd.py`` could define

```python
class MarosMeszarosDensePSD(MarosMeszarosDense):
```

And then wire this new test set up to ``benchmark.py`` at the root of the repository.

:warning: Don't forget to indicate in the description all assumptions that make it a subset of the full Maros-Meszaros test set, e.g.

```python
    @property
    def description(self) -> str:
        """Description of the test set."""
        return (
            "Subset of the Maros-Meszaros test set "
            "restricted to smaller dense problems "
            "and strictly positive definite Hessian matrices."
        )
```

In benchmarking, it is [of prime importance](http://plato.asu.edu/ftp/apology.pdf) to state the additional assumptions clearly when using subsets of well-known test sets.

**Comment by bodono** [comment]
You should be able to convert positive semi-definite matrices to second-order cone form too, using a Cholesky factorization where you throw away the zero columns (corresponding to zero eigenvalues). Ideally the timing to do this conversion would count towards the solvers total time, but that might be a pain.

**Comment by ottapav** [comment]
> You should be able to convert positive semi-definite matrices to second-order cone form too, using a Cholesky factorization where you throw away the zero columns (corresponding to zero eigenvalues). Ideally the timing to do this conversion would count towards the solvers total time, but that might be a pain.

Does it mean there is a approximation from convex to strictly convex QP? That would be great! Second-order cone is a new topic for me. Can you suggest an ilustrating reference, please? I can possibly implement inside the solver...

**Comment by bodono** [comment]
I just mean that [here](https://github.com/qpsolvers/qpsolvers/blob/dc9bd9419d41ff0ff9c6fcac00f47262e2196eb4/qpsolvers/conversions/socp_from_qp.py#L92) for positive semi-definite matrices we could just use a different decomp (looks like numpy cholesky only supports positive definite, so would have to use something else like svd).

**Comment by stephane-caron** [comment]
For instance Eigen's Cholesky decompositions are available in Python via [eigenpy](https://github.com/stack-of-tasks/eigenpy), including the LDLT which doesn't require the matrix to be definite.

We could definitely make it available in qpsolvers to improve the interface for ECOS. I've opened an issue at https://github.com/qpsolvers/qpsolvers/issues/179, I'll gladly help support a PR if somebody is willing to try it out.

**Comment by aescande** [comment]
> Ideally the timing to do this conversion would count towards the solvers total time, but that might be a pain.

To me it is essential that it does, the problem being that it should not take into account the possible python overhead.

**Comment by stephane-caron** [comment]
Thanks for your feedback. Let's continue this discussion in https://github.com/qpsolvers/qpsolvers_benchmark/issues/60 (ECOS) and https://github.com/qpsolvers/qpsolvers_benchmark/issues/12 (all solvers).

Back to this issue's initial topic: adding a ``maros_meszaros_dense_posdef`` subset to focus on solvers that require strictly-convex problems (e.g. quadprog has this requirement).
